export const GET_ALL_COURSE = "GET_ALL_COURSES"
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY"
export const CREATE_CATEGORY = "CREATE_CATEGORY"
export const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY"
export const GET_ERROR = "GET_ERROR"

export const GET_ALL_BRAND = "GET_ALL_BRAND"
export const CREATE_BRAND = "CREATE_BRAND"