export const GET_ALL_COURSE = "GET_ALL_COURSES"
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY"
export const CREATE_CATEGORY = "CREATE_CATEGORY"
export const CREATE_COURSE = "CREATE_COURSE"
export const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY"
export const GET_ERROR = "GET_ERROR"
export const GET_COURSE_ID = "GET_COURSE_ID"


export const GET_INSTRUCTOR_COURSES = "GET_INSTRUCTOR_COURSES"

export const CREATE_NEW_USER = "CREATE_NEW_USER"
export const LOGIN_USER = "LOGIN_USER"
export const GET_CURERNT_USER = "GET_CURERNT_USER"
export const FOREGT_PASSWORD = "FOREGT_PASSWORD"
export const VERIFY_PASSWORD = "VERIFY_PASSWORD"
export const RESET_PASSWORD = "RESET_PASSWORD"